name: CI
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  main:
    env:
      GOTOOLCHAIN: local
    strategy:
      fail-fast: false
      matrix:
        go: ["stable", "oldstable"]
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
      - run: go build ./cmd/usr-lib-apt-methods-oci
      - run: sudo cp -a usr-lib-apt-methods-oci /usr/lib/apt/methods/oci
      - run: |
          sudo tee /etc/apt/sources.list.d/oci.sources <<EOF
          Types: deb
          URIs: oci://ghcr.io/akihirosuda/apt-transport-oci-examples:latest
          Suites: stable
          Components: main
          Signed-By: /etc/apt/keyrings/apt-transport-oci-examples.gpg
          EOF
      - run: |
          curl -fsSL https://raw.githubusercontent.com/AkihiroSuda/apt-transport-oci-examples/refs/heads/master/apt-transport-oci-examples.gpg \
            | sudo gpg --dearmor -o /etc/apt/keyrings/apt-transport-oci-examples.gpg
      - run: sudo apt-get update
      - run: sudo apt-get install hello-apt-transport-oci
      - run: hello-apt-transport-oci
